# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - publish-chart-circle

jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout
      - run: mkdir /home/circleci/bin
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}      
      - run: wget -q https://get.helm.sh/helm-v3.5.2-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /home/circleci/bin/helm && chmod +x /home/circleci/bin/helm
      - run: make test
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  publish:
    docker:
      - image: quay.io/helmpack/chart-releaser:v1.1.1
    steps:
      ## Set CR_Token to GH Token
      ## package repo: cr package pachyderm
      ## create release: cr upload -o pachyderm -r helmchart
      ## cr index -o pachyderm -r helmchart -c https://pachyderm.github.io/helmchart --push
      - checkout
      - run: package pachyderm
      - run: upload -o pachyderm -r helmchart
      - run: index -o pachyderm -r helmchart -c https://pachyderm.github.io/helmchart --push
