---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dash
    suite: pachyderm
  name: dash
spec:
  ports:
  - name: dash-http
    port: 8080
    targetPort: dash-http
  - name: grpc-proxy-http
    port: 30081
    targetPort: grpc-proxy-http
  selector:
    app: dash
    suite: pachyderm
  type: LoadBalancer
